# Generated by Django 3.2 on 2021-05-13 04:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(verbose_name='Pinned')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('preview_image', models.ImageField(upload_to='banners/%Y/%m/%d/preview/', verbose_name='Preview image')),
                ('preview_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Preview text')),
                ('detail_image', models.ImageField(upload_to='banners/%Y/%m/%d/preview/detail/', verbose_name='Detail image')),
                ('detail_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Detail text')),
                ('publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='Expiration')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('-is_pinned', '-publication'),
            },
        ),
    ]
