# Generated by Django 3.2 on 2021-04-28 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/images/%Y/%m/%d/', verbose_name='Image')),
                ('url', models.URLField(verbose_name='URL')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published')),
                ('expired', models.DateTimeField(blank=True, null=True, verbose_name='Expired')),
                ('categories', models.ManyToManyField(to='banner.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ('-published', '-expired'),
            },
        ),
    ]
